### ISSUE TITLE
Put declaration of DNS-servers/resolvers out of script, but into an extra file that will be included if it exists

### ISSUE THREAD

**Issue by thomasmerz** [PeterDaveHello/chkdomain#12]
I would like to use your pretty and fancy script with different/additional DNS servers/resolvers:
```
80.69.96.12
45.90.28.39
45.90.30.39
1.1.1.1
1.0.0.1
8.8.8.8
8.8.4.4
208.67.222.222
208.67.220.220
84.200.69.80
84.200.70.40
9.9.9.11
149.112.112.11
192.168.0.1
192.168.42.241
192.168.0.13
46.182.19.48
194.150.168.168
5.1.66.255
185.150.99.255
80.241.218.68
159.69.114.157
176.9.93.198
176.9.1.117
94.140.14.14
94.140.15.15
94.140.14.140
94.140.14.141
95.215.19.53
185.253.5.0
193.110.81.0
193.110.81.9
185.253.5.9
76.76.2.38
76.76.2.39
```
I'm aware that I can update your script locally, but each update will overwrite my customized version.

So my idea is: put these DNS-servers/resolvers in an extra file that has an entry in `.gitignore` and move your suggested DNS-servers/resolvers into an extra file suffixed with `.sample` or `.template` and user your "template/suggestion" if not file without suffix can be found.

**Comment by PeterDaveHello** [comment]
That'll be more like a DNS propagation testing tool, right?

I wonder if just an additional file to add extra DNS resolvers could be useful enough for your need, without changing the heart of this project.

**Comment by thomasmerz** [comment]
Well, I forgot to mention that my list is totally unsorted… some are filtering, others are not. So my thoughts: make the list not static but some kind of "dynamic" to test more/other DNS servers/resolvers. If I find some time I will give you a PR (possibly be not this weekend) so you can see what I mean…

**Comment by PeterDaveHello** [comment]
@thomasmerz please take a look at #23 and see if it's good enough for you, thanks.

**Comment by PeterDaveHello** [comment]
Commit improved and merged, enjoy it and please feel free to report bugs.
