### ISSUE TITLE
Tiarap DNS seems to be unavailable in EU

### ISSUE THREAD

**Issue by thomasmerz** [PeterDaveHello/chkdomain#15]
I can't ping or query any of both DNS resolvers from different locations (Vodafone at my home, Hetzner from my cloudservers - all in the EU). But https://status.tiarap.net/ looks fine. 

I opened an [upstream issue](https://github.com/pengelana/blocklist/issues/150) in preparation for a PR to remove/comment Tiarap DNS if "needed".

**Comment by PeterDaveHello** [comment]
@thomasmerz thanks for the reporting, you're correct, just tested and verified the issue exists. Let's see how'd it go with upstream issue first ;)

**Comment by thomasmerz** [comment]
Problem has been solved in upstream issue 👍🏼
