### ISSUE TITLE
Freenom World DNS 80.80.80.80 seems to be unavailable in Germany

### ISSUE THREAD

**Issue by thomasmerz** [PeterDaveHello/chkdomain#16]
I observed a similar problem as in #15 with Freenom World DNS. I can't do DNS queries using 80.80.80.80, but 80.80.81.81 is working fine with Vodafone Provider and Hetzner Cloudserver in Germany. And 80.80.80.80 is working fine with my Hetzner Cloudserver in Finland.

I didn't find anything to make an issue for this, so do you also observe this behavior?

**Comment by PeterDaveHello** [comment]
It's strange, just tested from multiple Germany locations, none failed.

**Comment by thomasmerz** [comment]
Seems to be a temporary problem 🤷🏼‍♂️ Today it works! Sorry for the inconvenience… Maybe I should add both to my DNS-ping monitoring (https://thomasmerz.github.io/dnspingtest_rrd_ka/, https://thomasmerz.github.io/dnspingtest_rrd_hel/, https://thomasmerz.github.io/dnspingtest_rrd_hel/)… 💡
